name: 'aviation_lakehouse'
version: '1.0.0'
profile: 'aviation_lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  aviation_lakehouse:
    silver:
      staging:
        +materialized: view
      intermediate:
        +materialized: external
        +format: parquet
        +schema: silver_intermediate

    gold:
      marts:
        core:
          +materialized: external
          +format: parquet
          +schema: gold_core
        commercial:
          +materialized: external
          +format: parquet
          +schema: gold_commercial
        operations:
          +materialized: external
          +format: parquet
          +schema: gold_operations