name: 'aviation_lakehouse'
version: '1.0.0'
profile: 'aviation_lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  aviation_lakehouse:
    silver:
      staging:
        +materialized: view
      intermediate:
        +materialized: view
    gold:
      marts:
        +materialized: external
        +format: parquet
        +external_location: "s3://aviation-lakehouse/{name}.parquet"